package com.aliqo.app
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
private val ChallengeBg=Color(0xFF061126);private val ChallengeCard=Color(0xFF101C34);private val ChallengeWhite=Color(0xFFF7F9FF);private val ChallengeMuted=Color(0xFFAEB8D1);private val ChallengePurple=Color(0xFF7C32F2)
data class ChallengeGame(val icon:String,val title:String,val subtitle:String,val tag:String)
private val challengeGames=listOf(ChallengeGame("✊✋✌️","حجر ورقة مقص","اختر حركتك سرًا واكشف النتيجة مع خصمك","سريع"),ChallengeGame("🧠","تحدي التوافق","أجيبا عن نفس الأسئلة واكتشفا نسبة التوافق","توافق"),ChallengeGame("⚡","أسرع إجابة","سؤال وأربع اختيارات.. الأسرع بالصحيح يكسب","سرعة"),ChallengeGame("🎯","خمن اختيار خصمك","توقع ماذا سيختار خصمك قبل كشف الإجابة","تخمين"),ChallengeGame("🕵️","مين الكذاب؟","اكتشف العبارة المزيفة قبل خصمك","ذكاء"),ChallengeGame("🔢","الرقم السري","خمن الرقم باستخدام تلميحات أعلى وأقل","منطق"),ChallengeGame("🧩","فك الشفرة","حل الرموز والإيموجي قبل منافسك","ألغاز"),ChallengeGame("💣","لا تختار نفس الشيء","اختيارك سرّي.. لا تقع على نفس اختيار خصمك","نجاة"),ChallengeGame("👑","ملك التحدي","مواجهات جماعية متتابعة حتى يبقى ملك الساحة","جماعي"))
@Composable fun PremiumMatchExperience(auth:String,open:(ChatDto)->Unit){var mode by remember{mutableStateOf<String?>(null)};var selected by remember{mutableStateOf<ChallengeGame?>(null)};when{selected?.title=="حجر ورقة مقص"->RockPaperScissors(onBack={selected=null});selected!=null->ChallengePreview(selected!!,mode.orEmpty()){selected=null};mode!=null->ChallengePicker(mode!!,{mode=null}){selected=it};else->ChallengeLanding({mode="ONE"},{mode="GROUP"})}}
@Composable private fun ChallengeLanding(onOne:()->Unit,onGroup:()->Unit){Column(Modifier.fillMaxSize().background(ChallengeBg).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("⚔️ التحديات",color=ChallengeWhite,fontSize=28.sp,fontWeight=FontWeight.Black);Text("اختر نوع المواجهة",color=ChallengeWhite,fontSize=22.sp,fontWeight=FontWeight.Bold);Text("ادخل الساحة، اختبر مهارتك، واكسب المواجهة",color=ChallengeMuted);Mode("⚔️","1 ضد 1","واجه لاعبًا في تحديات سريعة ومباشرة",Color(0xFF6425C7),onOne);Mode("👥","جماعي","تحديات تجمع عدة لاعبين في ساحة واحدة",Color(0xFF0875C9),onGroup);Card(colors=CardDefaults.cardColors(containerColor=Color(0xFF25164E)),shape=RoundedCornerShape(22.dp)){Row(Modifier.fillMaxWidth().padding(17.dp),verticalAlignment=Alignment.CenterVertically){Text("🏆",fontSize=31.sp);Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text("بطولة الشهر",color=ChallengeWhite,fontWeight=FontWeight.Bold,fontSize=18.sp);Text("منافسة شهرية كبيرة",color=ChallengeMuted)};Text("قريبًا",color=Color(0xFFD7B7FF))}}}}
@Composable private fun Mode(icon:String,title:String,sub:String,color:Color,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),shape=RoundedCornerShape(23.dp),colors=CardDefaults.cardColors(containerColor=color)){Row(Modifier.fillMaxWidth().height(110.dp).padding(17.dp),verticalAlignment=Alignment.CenterVertically){Text(icon,fontSize=38.sp);Spacer(Modifier.width(15.dp));Column(Modifier.weight(1f)){Text(title,color=ChallengeWhite,fontSize=22.sp,fontWeight=FontWeight.Bold);Text(sub,color=ChallengeMuted)};Text("‹",color=ChallengeWhite,fontSize=30.sp)}}}
@Composable private fun ChallengePicker(mode:String,onBack:()->Unit,onSelect:(ChallengeGame)->Unit){val games=if(mode=="GROUP")challengeGames.filter{it.title in listOf("ملك التحدي","تحدي التوافق","أسرع إجابة","لا تختار نفس الشيء")}else challengeGames.filter{it.title!="ملك التحدي"};Column(Modifier.fillMaxSize().background(ChallengeBg).verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("‹",color=ChallengeWhite,fontSize=34.sp,modifier=Modifier.clickable(onClick=onBack));Spacer(Modifier.width(8.dp));Column{Text(if(mode=="GROUP")"👥 تحديات جماعية" else "⚔️ تحديات 1 ضد 1",color=ChallengeWhite,fontSize=25.sp,fontWeight=FontWeight.Black);Text("اختر لعبتك وادخل المواجهة",color=ChallengeMuted)}};games.forEach{g->Card(Modifier.fillMaxWidth().clickable{onSelect(g)},shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=ChallengeCard),border=BorderStroke(1.dp,Color(0xFF263650))){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(52.dp).background(Color(0xFF241B50),RoundedCornerShape(15.dp)),contentAlignment=Alignment.Center){Text(g.icon,fontSize=25.sp)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(g.title,color=ChallengeWhite,fontSize=17.sp,fontWeight=FontWeight.Bold);Text(g.subtitle,color=ChallengeMuted,fontSize=11.sp)};Text(g.tag,color=Color(0xFFC9B7FF));Spacer(Modifier.width(7.dp));Text("‹",color=ChallengeWhite,fontSize=25.sp)}}}}}
@Composable private fun ChallengePreview(game:ChallengeGame,mode:String,onBack:()->Unit){Column(Modifier.fillMaxSize().background(ChallengeBg).padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text(game.icon,fontSize=70.sp);Text(game.title,color=ChallengeWhite,fontSize=28.sp,fontWeight=FontWeight.Black);Text(game.subtitle,color=ChallengeMuted,textAlign=TextAlign.Center);Spacer(Modifier.height(24.dp));Button(onClick={},enabled=false,modifier=Modifier.fillMaxWidth()){Text("قريبًا — تجهيز نظام اللعب")};TextButton(onClick=onBack){Text("اختيار تحدٍ آخر",color=ChallengeMuted)}}}
private enum class RpsStage{INFO,SEARCH,PLAY,WAIT,RESULT,WIN}
@Composable private fun RockPaperScissors(onBack:()->Unit){var stage by remember{mutableStateOf(RpsStage.INFO)};var round by remember{mutableIntStateOf(1)};var mine by remember{mutableStateOf("")};var myScore by remember{mutableIntStateOf(0)};var enemy by remember{mutableIntStateOf(0)}
LaunchedEffect(stage){if(stage==RpsStage.SEARCH){delay(1300);stage=RpsStage.PLAY};if(stage==RpsStage.WAIT){delay(1000);myScore++;stage=RpsStage.RESULT}}
Column(Modifier.fillMaxSize().background(ChallengeBg).padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Row(Modifier.fillMaxWidth()){Text("‹",color=ChallengeWhite,fontSize=34.sp,modifier=Modifier.clickable{if(stage==RpsStage.INFO)onBack()else stage=RpsStage.INFO});Spacer(Modifier.weight(1f));if(stage!=RpsStage.INFO)Text("حجر ورقة مقص",color=ChallengeWhite,fontWeight=FontWeight.Bold,fontSize=20.sp)};Spacer(Modifier.weight(1f));when(stage){RpsStage.INFO->Info{stage=RpsStage.SEARCH};RpsStage.SEARCH->Search();RpsStage.PLAY->Play(round,myScore,enemy){mine=it;stage=RpsStage.WAIT};RpsStage.WAIT->WaitChoice(mine);RpsStage.RESULT->Result(mine,myScore,enemy){if(myScore>=2)stage=RpsStage.WIN else{round++;mine="";stage=RpsStage.PLAY}};RpsStage.WIN->Win(myScore,enemy,{round=1;myScore=0;enemy=0;stage=RpsStage.PLAY},onBack)};Spacer(Modifier.weight(1f))}}
@Composable private fun Info(start:()->Unit){Text("✊  ✋  ✌️",fontSize=54.sp);Text("حجر ورقة مقص",color=ChallengeWhite,fontSize=30.sp,fontWeight=FontWeight.Black);Text("اختر حركتك سرًا واكشف النتيجة مع خصمك",color=ChallengeMuted,textAlign=TextAlign.Center);Spacer(Modifier.height(24.dp));Surface(shape=RoundedCornerShape(18.dp),color=ChallengeCard){Column(Modifier.padding(18.dp)){Text("🎯  وضع 1 ضد 1",color=ChallengeWhite);Text("👥  3 جولات — الأول يفوز بجولتين",color=ChallengeWhite);Text("⚡  اختيارك سري حتى يختار الخصم",color=ChallengeWhite);Text("🏆  من يفوز بجولتين يحقق الانتصار",color=ChallengeWhite)}};Spacer(Modifier.height(30.dp));Button(start,Modifier.fillMaxWidth().height(55.dp),colors=ButtonDefaults.buttonColors(containerColor=ChallengePurple)){Text("ابدأ البحث عن خصم",fontWeight=FontWeight.Bold)}}
@Composable private fun Search(){Text("تم العثور على خصم!",color=ChallengeWhite,fontSize=28.sp,fontWeight=FontWeight.Black);Text("استعد للمواجهة...",color=ChallengeMuted);Spacer(Modifier.height(30.dp));Text("👤     VS     👤",fontSize=48.sp);Spacer(Modifier.height(30.dp));CircularProgressIndicator(color=ChallengePurple)}
@Composable private fun Score(round:Int,a:Int,b:Int){Text("الجولة $round من 3",color=ChallengeMuted);Spacer(Modifier.height(10.dp));Text("أنت   $a   ⚔️   $b   الخصم",color=ChallengeWhite,fontSize=20.sp,fontWeight=FontWeight.Bold)}
@Composable private fun Play(round:Int,a:Int,b:Int,choose:(String)->Unit){Score(round,a,b);Spacer(Modifier.height(38.dp));Text("3",color=Color(0xFFB889FF),fontSize=78.sp,fontWeight=FontWeight.Black);Text("اختر حركتك الآن!",color=ChallengeWhite,fontSize=24.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(22.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){listOf("✊" to "حجر","✋" to "ورقة","✌️" to "مقص").forEach{(e,n)->Card(Modifier.weight(1f).clickable{choose(n)},shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=ChallengeCard),border=BorderStroke(1.dp,Color(0xFF5635B5))){Column(Modifier.fillMaxWidth().padding(vertical=18.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(e,fontSize=38.sp);Text(n,color=ChallengeWhite,fontWeight=FontWeight.Bold)}}}}}
@Composable private fun WaitChoice(mine:String){Text(if(mine=="حجر")"✊" else if(mine=="ورقة")"✋" else "✌️",fontSize=75.sp);Text("تم اختيارك! ✓",color=ChallengeWhite,fontSize=27.sp,fontWeight=FontWeight.Black);Text("بانتظار اختيار الخصم...",color=ChallengeMuted);Spacer(Modifier.height(25.dp));CircularProgressIndicator(color=ChallengePurple)}
@Composable private fun Result(mine:String,a:Int,b:Int,next:()->Unit){Text("${if(mine=="حجر")"✊" else if(mine=="ورقة")"✋" else "✌️"}   VS   ✌️",fontSize=58.sp);Spacer(Modifier.height(25.dp));Surface(shape=RoundedCornerShape(22.dp),color=Color(0xFF063D32)){Column(Modifier.padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("🏆 فزت بالجولة!",color=Color(0xFF2DFFAA),fontSize=24.sp,fontWeight=FontWeight.Black);Text("النتيجة $a - $b",color=ChallengeWhite)}};Spacer(Modifier.height(28.dp));Button(next,Modifier.fillMaxWidth().height(54.dp),colors=ButtonDefaults.buttonColors(containerColor=ChallengePurple)){Text("الجولة التالية",fontWeight=FontWeight.Bold)}}
@Composable private fun Win(a:Int,b:Int,replay:()->Unit,back:()->Unit){Text("👑",fontSize=78.sp);Text("انتصار!",color=Color(0xFFFFC928),fontSize=42.sp,fontWeight=FontWeight.Black);Text("$a  -  $b",color=ChallengeWhite,fontSize=34.sp,fontWeight=FontWeight.Bold);Text("لقد فزت بالمواجهة",color=ChallengeMuted);Spacer(Modifier.height(30.dp));Button(replay,Modifier.fillMaxWidth().height(54.dp),colors=ButtonDefaults.buttonColors(containerColor=ChallengePurple)){Text("إعادة التحدي",fontWeight=FontWeight.Bold)};OutlinedButton(back,Modifier.fillMaxWidth()){Text("العودة للتحديات",color=ChallengeWhite)}}
