package com.aliqo.app

import android.media.AudioManager
import android.media.ToneGenerator
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import retrofit2.HttpException

private val ChallengeBg=Color(0xFF061126);private val ChallengeCard=Color(0xFF101C34);private val ChallengeWhite=Color(0xFFF7F9FF);private val ChallengeMuted=Color(0xFFAEB8D1);private val ChallengePurple=Color(0xFF7C32F2)
data class ChallengeGame(val icon:AliqoIcon,val title:String,val subtitle:String,val tag:String)
private val challengeGames=listOf(
 ChallengeGame(AliqoIcon.GAMEPAD,"حجر ورقة مقص","اختر حركتك سرًا واكشف النتيجة مع خصمك","سريع"),
 ChallengeGame(AliqoIcon.COMPAT,"تحدي التوافق","أجيبا عن نفس الأسئلة واكتشفا نسبة التوافق","توافق"),
 ChallengeGame(AliqoIcon.SPEED,"أسرع إجابة","سؤال وأربع اختيارات.. الأسرع بالصحيح يكسب","سرعة"),
 ChallengeGame(AliqoIcon.PREDICT,"خمن اختيار خصمك","توقع ماذا سيختار خصمك قبل كشف الإجابة","تخمين"),
 ChallengeGame(AliqoIcon.DETECTIVE,"مين الكذاب؟","اكتشف العبارة المزيفة قبل خصمك","ذكاء"),
 ChallengeGame(AliqoIcon.NUMBER,"الرقم السري","خمن الرقم باستخدام تلميحات أعلى وأقل","منطق"),
 ChallengeGame(AliqoIcon.PUZZLE,"فك الشفرة","حل الرموز قبل منافسك","ألغاز"),
 ChallengeGame(AliqoIcon.AVOID,"لا تختار نفس الشيء","اختيارك سرّي.. لا تقع على نفس اختيار خصمك","نجاة"),
 ChallengeGame(AliqoIcon.TROPHY,"ملك التحدي","مواجهات جماعية متتابعة حتى يبقى ملك الساحة","جماعي"))

@Composable fun PremiumMatchExperience(auth:String,onArenaChanged:(Boolean)->Unit={}){var mode by remember{mutableStateOf<String?>(null)};var selected by remember{mutableStateOf<ChallengeGame?>(null)};LaunchedEffect(mode,selected){if(selected?.title!="حجر ورقة مقص")onArenaChanged(false)};when{selected?.title=="حجر ورقة مقص"->RockPaperScissors(auth,onArenaChanged){selected=null};selected!=null->ChallengePreview(selected!!){selected=null};mode!=null->ChallengePicker(mode!!,{mode=null}){selected=it};else->ChallengeLanding({mode="ONE"},{mode="GROUP"})}}

@Composable private fun ChallengeLanding(onOne:()->Unit,onGroup:()->Unit){Column(Modifier.fillMaxSize().background(ChallengeBg).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){AliqoArenaIcon(AliqoIcon.SWORDS,size=34.dp);Spacer(Modifier.width(9.dp));Text("التحديات",color=ChallengeWhite,fontSize=28.sp,fontWeight=FontWeight.Black)};Text("اختر نوع المواجهة",color=ChallengeWhite,fontSize=22.sp,fontWeight=FontWeight.Bold);Text("ادخل الساحة، اختبر مهارتك، واكسب المواجهة",color=ChallengeMuted);Mode(AliqoIcon.SWORDS,"1 ضد 1","واجه لاعبًا في تحديات سريعة ومباشرة",Color(0xFF6425C7),onOne);Mode(AliqoIcon.ROOMS,"جماعي","تحديات تجمع عدة لاعبين في ساحة واحدة",Color(0xFF0875C9),onGroup);Card(colors=CardDefaults.cardColors(containerColor=Color(0xFF25164E)),shape=RoundedCornerShape(22.dp)){Row(Modifier.fillMaxWidth().padding(17.dp),verticalAlignment=Alignment.CenterVertically){AliqoArenaIcon(AliqoIcon.TROPHY,size=38.dp);Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text("بطولة الشهر",color=ChallengeWhite,fontWeight=FontWeight.Bold,fontSize=18.sp);Text("منافسة شهرية كبيرة",color=ChallengeMuted)};Text("قريبًا",color=Color(0xFFD7B7FF))}}}}
@Composable private fun Mode(icon:AliqoIcon,title:String,sub:String,color:Color,onClick:()->Unit){Card(Modifier.fillMaxWidth().clickable(onClick=onClick),shape=RoundedCornerShape(23.dp),colors=CardDefaults.cardColors(containerColor=color)){Row(Modifier.fillMaxWidth().heightIn(min=110.dp).padding(horizontal=17.dp,vertical=18.dp),verticalAlignment=Alignment.CenterVertically){AliqoArenaIcon(icon,size=43.dp);Spacer(Modifier.width(15.dp));Column(Modifier.weight(1f)){Text(title,color=ChallengeWhite,fontSize=22.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(3.dp));Text(sub,color=ChallengeMuted,lineHeight=20.sp)};Spacer(Modifier.width(8.dp));Text("‹",color=ChallengeWhite,fontSize=30.sp)}}}
@Composable private fun ChallengePicker(mode:String,onBack:()->Unit,onSelect:(ChallengeGame)->Unit){val games=if(mode=="GROUP")challengeGames.filter{it.title in listOf("ملك التحدي","تحدي التوافق","أسرع إجابة","لا تختار نفس الشيء")}else challengeGames.filter{it.title!="ملك التحدي"};Column(Modifier.fillMaxSize().background(ChallengeBg).verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("‹",color=ChallengeWhite,fontSize=34.sp,modifier=Modifier.clickable(onClick=onBack));Spacer(Modifier.width(8.dp));AliqoArenaIcon(if(mode=="GROUP")AliqoIcon.ROOMS else AliqoIcon.SWORDS,size=31.dp);Spacer(Modifier.width(8.dp));Column{Text(if(mode=="GROUP")"تحديات جماعية" else "تحديات 1 ضد 1",color=ChallengeWhite,fontSize=25.sp,fontWeight=FontWeight.Black);Text("اختر لعبتك وادخل المواجهة",color=ChallengeMuted)}};games.forEach{g->Card(Modifier.fillMaxWidth().clickable{onSelect(g)},shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=ChallengeCard),border=BorderStroke(1.dp,Color(0xFF263650))){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(52.dp).background(Color(0xFF241B50),RoundedCornerShape(15.dp)),contentAlignment=Alignment.Center){AliqoArenaIcon(g.icon,size=32.dp)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(g.title,color=ChallengeWhite,fontSize=17.sp,fontWeight=FontWeight.Bold);Text(g.subtitle,color=ChallengeMuted,fontSize=11.sp)};Text(g.tag,color=Color(0xFFC9B7FF));Spacer(Modifier.width(7.dp));Text("‹",color=ChallengeWhite,fontSize=25.sp)}}}}}
@Composable private fun ChallengePreview(game:ChallengeGame,onBack:()->Unit){Column(Modifier.fillMaxSize().background(ChallengeBg).padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){AliqoArenaIcon(game.icon,size=82.dp);Spacer(Modifier.height(12.dp));Text(game.title,color=ChallengeWhite,fontSize=28.sp,fontWeight=FontWeight.Black);Text(game.subtitle,color=ChallengeMuted,textAlign=TextAlign.Center);Spacer(Modifier.height(24.dp));Button(onClick={},enabled=false,modifier=Modifier.fillMaxWidth()){Text("قريبًا — تجهيز نظام اللعب")};TextButton(onClick=onBack){Text("اختيار تحدٍ آخر",color=ChallengeMuted)}}}
private enum class RpsScreen{INFO,SEARCH,GAME,ERROR}
private fun rpsErrorMessage(e:Exception):String{if(e is HttpException){val body=runCatching{e.response()?.errorBody()?.string()}.getOrNull()?.replace("\n"," ")?.take(260);return if(body.isNullOrBlank())"HTTP ${e.code()} — السيرفر لم يرسل تفاصيل" else "HTTP ${e.code()}\n$body"};val detail=e.message?.take(260)?:e.javaClass.simpleName;return "${e.javaClass.simpleName}\n$detail"}

@Composable private fun RockPaperScissors(auth:String,onArenaChanged:(Boolean)->Unit,onBack:()->Unit){var screen by remember{mutableStateOf(RpsScreen.INFO)};var sessionId by remember{mutableStateOf<String?>(null)};var game by remember{mutableStateOf(RpsStateDto())};var error by remember{mutableStateOf("")};var busy by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();val matchStartTone=remember{ToneGenerator(AudioManager.STREAM_MUSIC,90)}
 LaunchedEffect(screen){onArenaChanged(screen==RpsScreen.SEARCH||screen==RpsScreen.GAME)};DisposableEffect(Unit){onDispose{matchStartTone.release();onArenaChanged(false)}}
 LaunchedEffect(screen){if(screen==RpsScreen.SEARCH){try{error="";var match=rpsLiveApi.matchQueue(auth,MatchQueueRequest("ONE_V_ONE"));while(isActive&&screen==RpsScreen.SEARCH){if(match.state=="MATCHED"&&match.sessionId!=null){sessionId=match.sessionId;game=rpsLiveApi.state(auth,match.sessionId);matchStartTone.startTone(ToneGenerator.TONE_PROP_ACK,450);screen=RpsScreen.GAME;break};delay(1200);match=rpsLiveApi.matchStatus(auth)}}catch(e:CancellationException){throw e}catch(e:Exception){error=rpsErrorMessage(e);screen=RpsScreen.ERROR}}}
 LaunchedEffect(screen,sessionId){val id=sessionId?:return@LaunchedEffect;if(screen==RpsScreen.GAME)while(isActive&&screen==RpsScreen.GAME){delay(700);try{game=rpsLiveApi.state(auth,id)}catch(e:CancellationException){throw e}catch(_:Exception){}}}
 LaunchedEffect(screen,sessionId,game.phase,game.round,game.readyForNext){val id=sessionId?:return@LaunchedEffect;if(screen==RpsScreen.GAME&&game.phase=="RESULT"&&!game.readyForNext){delay(1000);try{game=rpsLiveApi.next(auth,id)}catch(e:CancellationException){throw e}catch(e:Exception){error=rpsErrorMessage(e)}}}
 Column(Modifier.fillMaxSize().background(ChallengeBg).padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){if(screen==RpsScreen.INFO)Text("‹",color=ChallengeWhite,fontSize=36.sp,modifier=Modifier.clickable{onBack()})else if(screen==RpsScreen.SEARCH)Text("‹",color=ChallengeWhite,fontSize=36.sp,modifier=Modifier.clickable{if(!busy)scope.launch{busy=true;try{rpsLiveApi.cancelQueue(auth)}catch(_:Exception){};screen=RpsScreen.INFO;sessionId=null;busy=false}})else if(screen==RpsScreen.ERROR)Text("‹",color=ChallengeWhite,fontSize=36.sp,modifier=Modifier.clickable{screen=RpsScreen.INFO;sessionId=null});Spacer(Modifier.weight(1f));if(screen!=RpsScreen.INFO)Text("حجر ورقة مقص",color=ChallengeWhite,fontWeight=FontWeight.Bold,fontSize=20.sp)};Spacer(Modifier.weight(1f));when(screen){RpsScreen.INFO->Info{screen=RpsScreen.SEARCH};RpsScreen.SEARCH->Search();RpsScreen.ERROR->{AliqoArenaIcon(AliqoIcon.AVOID,size=62.dp);Text("تشخيص بدء المواجهة",color=ChallengeMuted,fontSize=14.sp);Spacer(Modifier.height(8.dp));Text(error,color=ChallengeWhite,fontSize=17.sp,textAlign=TextAlign.Center);Spacer(Modifier.height(20.dp));Button(onClick={screen=RpsScreen.SEARCH},colors=ButtonDefaults.buttonColors(containerColor=ChallengePurple)){Text("إعادة المحاولة")}};RpsScreen.GAME->{val id=sessionId!!;if(!game.opponentOnline&&!game.finished){OpponentOffline(game.opponentReconnectSeconds);Spacer(Modifier.height(18.dp))};when(game.phase){"PLAY"->LivePlay(game){move->if(!busy)scope.launch{busy=true;try{game=rpsLiveApi.move(auth,id,RpsMoveRequest(move))}catch(e:CancellationException){throw e}catch(e:Exception){error=rpsErrorMessage(e)};busy=false}};"WAITING"->WaitChoice(game.myMove);"RESULT"->LiveResult(game);"FINISHED"->LiveFinished(game,{scope.launch{busy=true;try{game=rpsLiveApi.rematch(auth,id)}catch(e:CancellationException){throw e}catch(e:Exception){error=rpsErrorMessage(e)};busy=false}},{onArenaChanged(false);onBack()});else->CircularProgressIndicator(color=ChallengePurple)}}};if(error.isNotBlank()&&screen==RpsScreen.GAME){Spacer(Modifier.height(12.dp));Text(error,color=Color(0xFFFF9A9A),fontSize=12.sp,textAlign=TextAlign.Center)};Spacer(Modifier.weight(1f))}}

@Composable private fun Info(){ }
@Composable private fun Info(start:()->Unit){Row(horizontalArrangement=Arrangement.spacedBy(20.dp)){AliqoArenaIcon(AliqoIcon.ROCK,size=52.dp);AliqoArenaIcon(AliqoIcon.PAPER,size=52.dp);AliqoArenaIcon(AliqoIcon.SCISSORS,size=52.dp)};Spacer(Modifier.height(12.dp));Text("حجر ورقة مقص",color=ChallengeWhite,fontSize=30.sp,fontWeight=FontWeight.Black);Text("اختر حركتك سرًا واكشف النتيجة مع خصمك",color=ChallengeMuted,textAlign=TextAlign.Center);Spacer(Modifier.height(24.dp));Surface(shape=RoundedCornerShape(18.dp),color=ChallengeCard){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Rule(AliqoIcon.SWORDS,"وضع 1 ضد 1");Rule(AliqoIcon.NUMBER,"المباراة 10 جولات كاملة");Rule(AliqoIcon.TROPHY,"كل فوز = نقطة، والتعادل بدون نقطة");Rule(AliqoIcon.TROPHY,"الأعلى نقاطًا بعد الجولة العاشرة يفوز")}};Spacer(Modifier.height(30.dp));Button(start,Modifier.fillMaxWidth().height(55.dp),colors=ButtonDefaults.buttonColors(containerColor=ChallengePurple)){Text("ابدأ البحث عن خصم",fontWeight=FontWeight.Bold)}}
@Composable private fun Rule(icon:AliqoIcon,text:String){Row(verticalAlignment=Alignment.CenterVertically){AliqoArenaIcon(icon,size=23.dp);Spacer(Modifier.width(10.dp));Text(text,color=ChallengeWhite)}}
@Composable private fun Search(){Text("جارٍ البحث عن خصم...",color=ChallengeWhite,fontSize=27.sp,fontWeight=FontWeight.Black);Text("يمكنك الرجوع وإلغاء البحث قبل دخول المباراة",color=ChallengeMuted);Spacer(Modifier.height(30.dp));Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(18.dp)){AliqoArenaIcon(AliqoIcon.PLAYER,size=54.dp);Text("VS",color=Color(0xFFFFC857),fontSize=24.sp,fontWeight=FontWeight.Black);AliqoArenaIcon(AliqoIcon.PLAYER,size=54.dp)};Spacer(Modifier.height(30.dp));CircularProgressIndicator(color=ChallengePurple)}
@Composable private fun Score(g:RpsStateDto){Text("الجولة ${g.round} من ${g.totalRounds}",color=ChallengeMuted);Spacer(Modifier.height(10.dp));CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceEvenly){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("الخصم",color=ChallengeMuted,fontWeight=FontWeight.Bold);Text("${g.opponentScore}",color=ChallengeWhite,fontSize=24.sp,fontWeight=FontWeight.Black)};AliqoArenaIcon(AliqoIcon.SWORDS,size=25.dp);Column(horizontalAlignment=Alignment.CenterHorizontally){Text("أنت",color=Color(0xFFB98CFF),fontWeight=FontWeight.Black);Text("${g.myScore}",color=ChallengeWhite,fontSize=24.sp,fontWeight=FontWeight.Black)}}}}
@Composable private fun ResultScore(g:RpsStateDto,fontSize:Int=28){CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("الخصم",color=ChallengeMuted,fontSize=11.sp);Text("${g.opponentScore}",color=ChallengeWhite,fontSize=fontSize.sp,fontWeight=FontWeight.Bold)};Text("-",color=ChallengeWhite,fontSize=fontSize.sp,fontWeight=FontWeight.Bold);Column(horizontalAlignment=Alignment.CenterHorizontally){Text("أنت",color=Color(0xFFB98CFF),fontSize=11.sp);Text("${g.myScore}",color=ChallengeWhite,fontSize=fontSize.sp,fontWeight=FontWeight.Bold)}}}}
private fun moveIcon(move:String?)=when(move){"ROCK"->AliqoIcon.ROCK;"PAPER"->AliqoIcon.PAPER;"SCISSORS"->AliqoIcon.SCISSORS;else->AliqoIcon.GAMEPAD}
@Composable private fun MoveSymbol(move:String?,size:Int=62){AliqoArenaIcon(moveIcon(move),size=size.dp)}
@Composable private fun LivePlay(g:RpsStateDto,choose:(String)->Unit){Score(g);Spacer(Modifier.height(35.dp));Text("اختر حركتك الآن!",color=ChallengeWhite,fontSize=24.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(22.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){listOf(Triple(AliqoIcon.ROCK,"حجر","ROCK"),Triple(AliqoIcon.PAPER,"ورقة","PAPER"),Triple(AliqoIcon.SCISSORS,"مقص","SCISSORS")).forEach{(icon,name,move)->Card(Modifier.weight(1f).clickable{choose(move)},shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=ChallengeCard),border=BorderStroke(1.dp,Color(0xFF5635B5))){Column(Modifier.fillMaxWidth().padding(vertical=18.dp),horizontalAlignment=Alignment.CenterHorizontally){AliqoArenaIcon(icon,size=43.dp);Spacer(Modifier.height(7.dp));Text(name,color=ChallengeWhite,fontWeight=FontWeight.Bold)}}}}}
@Composable private fun WaitChoice(move:String?){MoveSymbol(move,78);Spacer(Modifier.height(12.dp));Text("تم اختيارك! ✓",color=ChallengeWhite,fontSize=27.sp,fontWeight=FontWeight.Black);Text("بانتظار اختيار الخصم...",color=ChallengeMuted);Spacer(Modifier.height(25.dp));CircularProgressIndicator(color=ChallengePurple)}
@Composable private fun LiveResult(g:RpsStateDto){Score(g);Spacer(Modifier.height(30.dp));CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Ltr){Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(17.dp)){MoveSymbol(g.opponentMove);Text("VS",color=Color(0xFFFFC857),fontWeight=FontWeight.Black);MoveSymbol(g.myMove)}};Spacer(Modifier.height(25.dp));val title=when(g.roundResult){"WIN"->"فزت بالجولة!";"LOSE"->"خسرت الجولة";else->"تعادل"};val accent=when(g.roundResult){"WIN"->Color(0xFF2DFFAA);"LOSE"->Color(0xFFFF7D7D);else->Color(0xFFFFD66B)};Surface(shape=RoundedCornerShape(22.dp),color=ChallengeCard){Column(Modifier.padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){if(g.roundResult=="WIN")AliqoArenaIcon(AliqoIcon.TROPHY,size=35.dp);Text(title,color=accent,fontSize=24.sp,fontWeight=FontWeight.Black);ResultScore(g)}};Spacer(Modifier.height(18.dp));Text(if(g.readyForNext)"جارٍ بدء الجولة التالية..." else "النتيجة تظهر لثانية واحدة",color=ChallengeMuted)}
@Composable private fun OpponentOffline(seconds:Int){Surface(shape=RoundedCornerShape(18.dp),color=Color(0xFF20182F)){Column(Modifier.fillMaxWidth().padding(14.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("الخصم غير متصل",color=Color(0xFFFFC857),fontWeight=FontWeight.Bold);Text(if(seconds>0)"ننتظر عودته… ${seconds}ث" else "جارٍ إنهاء المواجهة…",color=ChallengeMuted,fontSize=12.sp)}}}
@Composable private fun LiveFinished(g:RpsStateDto,replay:()->Unit,back:()->Unit){val draw=g.myScore==g.opponentScore&&!g.endedByDisconnect;val won=g.wonMatch||(!draw&&g.myScore>g.opponentScore);AliqoArenaIcon(if(won)AliqoIcon.TROPHY else AliqoIcon.SWORDS,size=78.dp);Text(if(g.endedByDisconnect&&won)"انتصار بانسحاب الخصم" else if(g.endedByDisconnect)"انتهت المواجهة" else if(won)"انتصار" else if(draw)"تعادل" else "انتهت المواجهة",color=if(won)Color(0xFFFFC928)else if(draw)Color(0xFFFFD66B)else ChallengeWhite,fontSize=34.sp,fontWeight=FontWeight.Bold,textAlign=TextAlign.Center);ResultScore(g,34);Text(if(g.endedByDisconnect&&won)"لم يعد الخصم خلال مهلة الاتصال" else if(g.endedByDisconnect)"انتهت المواجهة بسبب الانقطاع" else if(won)"جمعت نقاطًا أكثر وفزت بالمواجهة" else if(draw)"انتهت الجولات العشر بالتعادل" else "جمع الخصم نقاطًا أكثر",color=ChallengeMuted,textAlign=TextAlign.Center);Spacer(Modifier.height(30.dp));Button(replay,Modifier.fillMaxWidth().height(54.dp),enabled=!g.rematchRequestedByMe,colors=ButtonDefaults.buttonColors(containerColor=ChallengePurple,disabledContainerColor=Color(0xFF342052))){Text(when{g.rematchRequestedByMe->"بانتظار موافقة الخصم…";g.rematchRequestedByOpponent->"قبول إعادة التحدي";else->"إعادة التحدي"},fontWeight=FontWeight.Bold)};if(g.rematchRequestedByOpponent&&!g.rematchRequestedByMe){Text("الخصم طلب إعادة التحدي",color=Color(0xFFB98CFF),fontSize=12.sp)};OutlinedButton(back,Modifier.fillMaxWidth()){Text("العودة للتحديات",color=ChallengeWhite)}}
